Server:
  Port: localhost:8080

Kafka:
  brokers:
    - localhost:9092
  UpstreamTopic: transactions-upstream
  HandleTopic: transactions-handle
  ConsumerGroupID: user-service
  BatchSize: 10
  MaxWait: 5s

Cron:
  Processor:
    Spec: "*/15 * * * * *"
